修正文字
goodjoblife/WorkTimeSurvey pull request #308
Opened 2016-09-27 03:12 UTC by barry800414

to fix #306 
並且將使用者條款、隱私權政策的文字修正。

2016-09-27 03:17 UTC, mark86092 reviewed
想問，`中文 English 中間要空白？`，或是 `中文English中間不要空白？`

2016-09-27 03:44 UTC, mark86092 commented
@barry800414 @wutingy 一開始有講什麼空白的規則嗎？

2016-09-27 03:47 UTC, wutingy commented
沒討論到，不過我覺得有空白會比較好，閱讀起來比較舒服

2016-09-27 05:33 UTC, barry800414 commented
我其實原本有空白，是當然有人反應不確定哪邊怪怪的?
Tin妳可以告訴我怎麼樣比較好嗎? 或是交給妳修

2016-09-27 05:34 UTC, mark86092 commented
會不會那時是在討論：`單純使用 GoodJob 服務 查詢工時之行為` 服務跟查詢這兩詞間的空白？

2016-09-27 05:35 UTC, barry800414 commented
ok, 看起來是 中英文間有空白就好
I'll fix it

2016-09-27 05:36 UTC, mark86092 commented
其實我都不是很確定，忘了太多了XD

2016-09-27 10:29 UTC, mark86092 requested changes
Some minor fix

2016-09-27 10:29 UTC, mark86092 commented on src/views/privacy-policy.pug
> +				li 以下的隱私權宣告，適用於您在使用GoodJob的產品、軟體、網站或服務(以下簡稱「GoodJob 服務」)，所涉及的「個人身分資訊」以及「使用者指定分享之資訊」的蒐集、運用與保護。
`使用 GoodJob 的`

2016-09-27 10:29 UTC, mark86092 commented on src/views/user-term.pug
> +				li GoodJob服務所呈現的所有內容，包含文字、數值、標記、圖片、聲音、影片、資訊、訊息或其他資料(以下簡稱「內容」)，皆由內容之提供者負所有責任與義務。此外，本網站有權刪除受爭議的內容。
`GoodJob 服務`

2016-09-27 10:50 UTC, wutingy commented on src/views/index.pug
> +								input(type="text" placeholder="8或8.5" id="form-day-promised-work-time" name="day_promised_work_time" class="is-required")
placeholder 是否也需要空格一下？

2016-09-28 03:43 UTC, mark86092 commented
@barry800414 Need some minor fixes

2016-09-28 05:37 UTC, barry800414 commented
我修好了! Please review it

2016-09-28 05:44 UTC, mark86092 approved these changes

2016-09-28 05:47 UTC, merged