show 頁面 搜尋框 改善
goodjoblife/WorkTimeSurvey pull request #310
Opened 2016-09-27 05:14 UTC by xxhomey19

2016-09-27 14:31 UTC, mark86092 commented
Please don't merge `goodjoblife:dev` into your branch `improve-search-bar` (it has no conflict), can you reset it?

2016-09-27 14:33 UTC, mark86092 commented on src/js/main/show.js
> +    setInputInfo: function(search_type, keyword) {
you can use `function(search_type = "by-company", keyword = "")`, we use babel to compile it

2016-09-27 14:36 UTC, mark86092 commented on src/js/main/show.js
> +    let deCodeName = decodeURIComponent(name);
`const decodeName` or `const decode_name`

2016-09-27 16:44 UTC, xxhomey19 commented on src/js/main/show.js
> +    setInputInfo: function(search_type, keyword) {
I don't get it.
It will have error when I change to `function(search_type = "by-company", keyword = "")`

2016-09-27 16:46 UTC, mark86092 commented on src/js/main/show.js
> +    setInputInfo: function(search_type, keyword) {
what's the error?

2016-09-27 16:51 UTC, xxhomey19 commented
Did I really reset it ?
Sorry, I'm not sure whether what I did is correct QQ

2016-09-27 16:52 UTC, xxhomey19 commented on src/js/main/show.js
> +    setInputInfo: function(search_type, keyword) {
Not be able to compile

2016-09-27 17:12 UTC, mark86092 commented on src/js/main/show.js
> +    setInputInfo: function(search_type, keyword) {
I use this, and get 

![image](https://cloud.githubusercontent.com/assets/1908007/18884084/923e7af2-8518-11e6-8934-f4670470ddb8.png)

![image](https://cloud.githubusercontent.com/assets/1908007/18884107/a1e00fde-8518-11e6-9cad-e7ef61331230.png)

2016-09-27 17:14 UTC, mark86092 commented on src/js/main/show.js
> +    setInputInfo: function(search_type, keyword) {
這樣寫的目的是可以把 setDefault 取代成一般的情況

2016-09-27 17:16 UTC, xxhomey19 commented on src/js/main/show.js
> +    setInputInfo: function(search_type, keyword) {
Oh yes. Sorry I misunderstand what your mean haha.
This is great

2016-09-27 17:19 UTC, mark86092 commented
git 的指令我再跟你用 slack 說明

2016-09-28 03:22 UTC, mark86092 approved these changes
看起來ＯＫ的，再給 @barry800414 review 一下

2016-09-28 05:20 UTC, barry800414 commented on src/js/main/show.js
> +    let deCodeName = decodeURIComponent(name);
I suggest `decoded_name` or `decodedName`

2016-09-28 05:27 UTC, barry800414 requested changes
除了變數名稱要修一下，我想沒有問題! 
另外想問的是，搜尋空白字元這件事，有要在這個PR做嗎?

2016-09-28 05:50 UTC, mark86092 commented
@barry800414 關於空白，我想先在 https://github.com/goodjoblife/WorkTimeSurvey/blob/dev/src/views/show.pug#L29

`input(required)` 這裡做處理好了（新 PR）

2016-09-28 06:16 UTC, xxhomey19 commented
所以我改一下變數名稱就OK了嗎～
還是連input(required)也要

2016-09-28 06:19 UTC, mark86092 commented
input 那個另外處理

2016-09-28 11:47 UTC, mark86092 commented
@barry800414 The PR is updated! tks

2016-09-28 17:19 UTC, merged

2016-09-29 02:19 UTC, barry800414 commented on src/js/main/show.js
>      searchBarApp.setInputInfo("by-job-title", deCodeName);
後面的變數名稱沒改，連搜尋都不能搜尋。
之後有改一定要先測試過。