Add default autocomplete
goodjoblife/WorkTimeSurvey pull request #314
Opened 2016-09-27 15:26 UTC by peteranny

When user focuses on `input.job_title` and `input.company_query` before typing any characters, the list of the top _n_ recently provided job_title/company_query are shown to the user.

This hints that the input fields have auto-completion-like function.

2016-09-27 16:56 UTC, mark86092 reviewed
Here's my review, thanks for submitting PR.

2016-09-27 16:56 UTC, mark86092 commented on src/js/main/index.js
> +    });
You can consider this: `$.map(res.workings, (item, i) => item.company.name)`

2016-09-27 16:56 UTC, mark86092 commented on src/js/main/index.js
> +    });
@wutingy Can you help include Polyfill into the whole project? (it seems needed here for the support of es5)

2016-09-27 16:56 UTC, mark86092 commented on src/js/main/index.js
> +            )).slice(0,8);
看起來是只有取 8 個而非 10 個嗎？

2016-09-27 16:56 UTC, mark86092 commented on src/js/main/index.js
> +            }
Can you change the variable `curr` into `$active_item` or some name? It is more readable

2016-09-27 16:56 UTC, mark86092 commented on src/js/main/index.js
> +    };
Can you explain `.data("ui-autocomplete")._renderItem = function xxx` mean?

2016-09-27 17:00 UTC, mark86092 commented on src/js/main/index.js
> +    };
應該是說，說一下為什麼使用這個

2016-09-27 17:31 UTC, peteranny commented on src/js/main/index.js
> +            )).slice(0,8);
對，隨意取的數字，覺得10個看起來有點多，反正這個list的目的只是讓人知道有auto-complete，而且也不太可能剛好就在這個list找到他想要的

2016-09-27 17:34 UTC, peteranny commented on src/js/main/index.js
> +    });
請問修改好之後，是再PR一次嗎？還是在這個PR做什麼設定就可修改？

2016-09-27 17:36 UTC, mark86092 commented on src/js/main/index.js
> +    });
直接在這個分支改，PR 會自動耕新

2016-09-27 17:56 UTC, mark86092 commented on src/js/main/index.js
> +            var $active_item = $(event.$active_itementTarget).find('.ui-state-active');
`$active_itementTarget` 這個是什麼？

2016-09-27 17:57 UTC, peteranny commented on src/js/main/index.js
> +    };
```
$("#form-company-query").data("ui-autocomplete")._renderItem = function(ul,item){
    // render each item in ui.content as a <li> element
    var li = $("<li>").append($("<div>").text(item.label));

    // put .ui-state-disabled on disabled items (e.g. 最近被填寫的公司)
    if(item.disabled) li.addClass("ui-state-disabled");

    return li.appendTo(ul);
}
```

只比原本的function多加了addClass

2016-09-27 18:15 UTC, peteranny commented on src/js/main/index.js
> +            var $active_item = $(event.$active_itementTarget).find('.ui-state-active');
改壞了，我重新push

2016-09-28 01:30 UTC, barry800414 commented
![image](https://cloud.githubusercontent.com/assets/3805975/18897551/cb484e64-855d-11e6-800e-09222e3828c9.png)
在想，數量要不要再少一些，大約三到五個?

2016-09-28 02:05 UTC, mark86092 requested changes
再麻煩你修正個幾個東西，其它部分我覺得很完整了

2016-09-28 02:05 UTC, mark86092 commented on src/js/main/index.js
> +    var default_company_names = [];
關於用 var 的部分，想請你做個修正：
1. 如果變數不會被重新 assign，就用 const
2. 如果變數是需要被重新 assign，用 let

2016-09-28 02:05 UTC, mark86092 commented on src/js/main/index.js
> +                    return {"value":v, disabled:i==0};
這裡需要你多一個欄位，這是剛發現的小 bug：

```
{
    value: v,
    disabled: i == 0,
    company_id: ??? // --> 這邊要放上公司的 id，應該會修改到 default_company_names 的結構
}
```

主因是底下的 code 會用到 (L417, L418)

```
$company_query.trigger('autocomplete-select', ui.item.company_id);
$("#form-company-id").val(ui.item.company_id);
```

2016-09-28 03:11 UTC, barry800414 commented on src/js/main/index.js
> +                $.map(res.workings, (item,i)=>item.company.name)
關於這邊，想說可以修改成:
當 `item.company.id === undefined` 的時候，這個 item.company.name就不要加入array裡面。
原因是，它有可能是使用者自己打的公司名稱(簡短的那種)，其實並不打算鼓勵使用者去選這個選項
不過這樣的話，醫院、非營利組織那類的，就不會顯示。因為我們沒有這些單位的統編。

2016-09-28 03:13 UTC, barry800414 commented
我覺得已經很完整，而且這方法非常聰明，把細節修一下，就沒問題了!

2016-09-28 03:17 UTC, mark86092 commented on src/js/main/index.js
> +                $.map(res.workings, (item,i)=>item.company.name)
我是覺得兩個方向都可以，補充：我覺得如果使用者輸入的公司名稱，如果很多人都會挑選，代表它是常用的，不如把它加入資料庫內（？）
@barry800414 你覺得一個ＯＫ的就好，畢竟這裡的原意是提醒有 autocomplete

2016-09-28 15:13 UTC, peteranny commented
已修正

2016-09-28 15:46 UTC, mark86092 commented on src/js/main/index.js
> +                    "id": item.company.id,
due to L429 `nameList.push({value: item.name, company_id: item.id});`, the `id: item.company.id` in L329 should be `company_id: item.company.id`

2016-09-28 17:16 UTC, peteranny commented on src/js/main/index.js
> +                    "id": item.company.id,
Revised

2016-09-28 17:18 UTC, mark86092 approved these changes

2016-09-28 17:19 UTC, merged

2016-09-29 01:10 UTC, barry800414 commented on src/js/main/index.js
> +                $.map(res.workings, (item,i)=>item.company.name)
這個有一部份的工會是要人工處理。
e.g. 台積電 & 台灣積體電路ooxx 這兩個其實是同家公司
這個還沒有很仔細的想要如何處理