eslint, adjust some code
goodjoblife/WorkTimeSurvey pull request #316
Opened 2016-09-28 17:36 UTC by mark86092

2016-10-11 01:53 UTC, barry800414 commented
想問一下，是之後code都會自動經過eslint重新排版嗎?
如果是的話，我覺得ok，不過這個PR有一些conflicts。
如果需要手動打指令，請跟我們說指令。

2016-10-11 01:56 UTC, mark86092 commented
不會自動，也不會偵測，只是清理這一次

2016-10-13 01:06 UTC, barry800414 requested changes
除了conflicts要解以外，我覺得ok!

2016-10-29 06:39 UTC, mark86092 commented
Close, I'll open new one

2016-10-29 06:45 UTC, closed without merging