工時查詢頁面搜尋欄的自動完成功能
goodjoblife/WorkTimeSurvey pull request #318
Opened 2016-09-29 02:29 UTC by barry800414

to solve #292

2016-09-29 02:38 UTC, mark86092 commented
autocomplete 跟 searchBarApp 應該沒有相依，可以把它搬出去減少相依

2016-09-29 02:41 UTC, barry800414 commented
想問一下，如果是像這樣:
```
const searchBarApp = new Vue({
  el: "#section-search",
  data: {
    search_type: "by-company",
    keyword: "",
  },
```
我要怎麼access searchBarApp 裡面的data?

2016-09-29 02:42 UTC, mark86092 commented
`$("#search-input").val()` 這個呢？

2016-09-29 02:44 UTC, peteranny commented
searchBarApp.$data
這樣試試

2016-09-29 02:44 UTC, mark86092 commented
原本的 autocomplete 應該是因為在 template 中，所以不得不這樣處理，這裡可以的話，想想看怎麼樣比較清楚

2016-09-29 02:48 UTC, mark86092 commented
`searchBarApp.keyword` 也可以

2016-09-29 12:40 UTC, mark86092 requested changes
修正一下，感謝

2016-09-29 12:40 UTC, mark86092 commented on src/js/main/show.js
> +    }
the select part is not necessary, the `searchBarApp` will update so

2016-09-29 12:40 UTC, mark86092 commented on src/views/show.pug
> +					input(type="text" placeholder="輸入公司 / 單位名稱" class="search-bar__input" id="search-input" name="keyword" v-model="keyword")
改成 `search-bar-input` 應該會好一點（我們在 search-bar 的地方）

或是用 `form-keyword-input`

2016-09-30 17:14 UTC, mark86092 approved these changes

2016-09-30 17:14 UTC, merged