Use Vue.http instead of $.ajax
goodjoblife/WorkTimeSurvey pull request #396
Opened 2017-01-14 17:06 UTC by mark86092

2017-01-16 14:36 UTC, barry800414 requested changes

2017-01-16 14:36 UTC, barry800414 commented on src/js/main/show.js
>            const nameList = $.map(res, (item, i) => ({
這邊`res`需要改成`res.data`，因為`res`是整個response 
像這樣:
`Object { url: "http://localhost:12000/workings/com…", body: "[{"_id":{"name":"AA"}}]", headers: Object, status: 200, statusText: "OK", ok: true, data: Array[1] }`

2017-01-16 14:38 UTC, barry800414 requested changes

2017-01-16 14:38 UTC, barry800414 commented on src/js/main/show.js
> +          const nameList = $.map(res, (item, i) => ({
這個地方也是  
`res` -> `res.data`

2017-01-16 14:38 UTC, barry800414 commented
其他部份我看沒有問題

2017-01-16 14:44 UTC, mark86092 commented on src/js/main/show.js
> +          const nameList = $.map(res, (item, i) => ({
同 #380，不使用 res.data

2017-01-16 14:48 UTC, mark86092 commented
Bug 已修正

2017-01-17 01:38 UTC, barry800414 approved these changes
I've done my review.

2017-01-17 01:45 UTC, merged