prevent currentView from search results for unauthed users
goodjoblife/WorkTimeSurvey pull request #402
Opened 2017-01-16 14:55 UTC by peteranny

prevent currentView from search view for unauthorized users

2017-01-17 06:12 UTC, barry800414 commented
這個PR的解釋有點不太懂。目前的理解是如果跳到以公司查或以職稱查的時候，如果沒有登入或有登入但沒有權限的話，網頁下方顯示的資料還是最新薪時的欄位。

可是我覺得不能這樣做耶..
舉個例子，明明是以公司蒐的網址，卻對應到最新薪時滿怪的，我是覺得要直接跳轉，或是提醒使用者沒有權限後跳轉。

另外，這邊沒有考慮到單筆資料的其他可能，例如: 工時排行榜，沒有權限的情況下應該也要跳轉。

2017-01-17 13:58 UTC, peteranny commented
跳轉和直接換currentView是一樣的意思吧？而且這樣最能有效防沒權限的使用者
用跳轉的就有時間差，讓使用者有看到搜尋結果的機會（也有因為我寫跳轉寫出滿多bug啦ㄏㄏ）

但真的需要有一段文字說明在有權限之前，都只能看薪時
不過想問一下這style需要我來弄嗎？還是Tin弄比較好？

2017-01-17 14:14 UTC, barry800414 commented
> 跳轉和直接換currentView是一樣的意思吧？

不一樣，我現在看網址是那樣，可是下面區塊卻跟網址不一致，很奇怪。

> 用跳轉的就有時間差，讓使用者有看到搜尋結果的機會

這個不可能啦你放心，後端會擋

> 但真的需要有一段文字說明在有權限之前，都只能看薪時

@wutingy 想問~  有現成的modal可以用嗎?

2017-01-17 15:02 UTC, wutingy commented
> 需要有一段文字說明在有權限之前，都只能看薪時
這個，我原本的想法是，就直接用現在最新資料那邊的 view，就好，應該不用特別寫？

2017-01-17 15:04 UTC, mark86092 commented
跳轉和直接換currentView 差在

1. 跳轉是引發路由轉變，再透過 router 去使 app 有完整的 flow 與資料讀取
2. 直接設定 currentView 會導致底下的 component 沒有更新（router 底下設定  currentViw 有很多行，只複製一行會造成不一致），與網址的改變

2017-01-17 15:05 UTC, mark86092 commented
跳轉走對的話應該會走到這裡，所以這個提示已經有了

![image](https://cloud.githubusercontent.com/assets/1908007/22025667/4d9422b4-dd09-11e6-812a-ab3cb196fd6b.png)

2017-01-17 16:13 UTC, peteranny commented
雖然好像剛 @mark86092 剛好開了另一個PR.....

總之現在我這個PR用自己的解法解掉state和router的問題
在state加上has_tried，在跳轉之前會先檢查state是否已經更新(has_tried=true)
更新後的state說使用者沒有權限才會跳轉

2017-01-17 16:21 UTC, mark86092 commented
基本上我那邊是沒有解決權限的問題，不過有先鋪路，我看一下你的解法

2017-01-18 03:57 UTC, barry800414 requested changes

2017-01-18 03:57 UTC, barry800414 commented on src/js/global/constant.js
> +  backendURL: 'http://wts-test.markchen.cc/',
這個不用commit上來喔

2017-01-18 03:57 UTC, barry800414 commented on src/js/main/show.js
> +    && (searchBarApp.search_type !== 'by-company' ||
我想問為什麼 `search_type` 要不等於 'by-company' ?

2017-01-18 03:57 UTC, barry800414 commented on src/js/main/show.js
> +  if( showjs_store.has_tried && !showjs_store.state.is_authed
假如 `has_tried` = true的情況才會跳轉，感覺怪怪的??

2017-01-18 03:57 UTC, barry800414 commented on src/js/main/show.js
> +    showjs_store.has_tried = true;
為什麼這邊要設為true呢?

2017-01-18 12:27 UTC, peteranny commented on src/js/global/constant.js
> +  backendURL: 'http://wts-test.markchen.cc/',
已修正

2017-01-18 12:33 UTC, peteranny commented on src/js/main/show.js
> +    showjs_store.has_tried = true;
我補上註解了

`has_tried`指的是頁面載入後FB SDK是否已經馬上嘗試登入
因為`router`和`showjs_store.state`都需要觸發是否跳轉的檢查，但跳轉的條件是

1. `showjs_store.state`說使用者沒登入或沒權限
2. `router`轉到非最新時薪

這兩個並不保證誰先誰後好，所以兩個我都設定檢查是否跳轉
而檢查時用`has_tried`來確保第1點已經做完 (第2點偷懶沒做...)

回到你的問題，這裡`has_tried=true`表示FB已經檢查是否登入了
這是要給`router`跑完檢查是否跳轉時用的

2017-01-18 12:33 UTC, peteranny commented on src/js/main/show.js
> +  if( showjs_store.has_tried && !showjs_store.state.is_authed
同上

2017-01-18 12:34 UTC, peteranny commented on src/js/main/show.js
> +    && (searchBarApp.search_type !== 'by-company' ||
你不是說工時排行也要檔？？ (工時排行為`by-worktime`，總共只有這兩種type)

2017-01-18 13:09 UTC, barry800414 commented on src/js/main/show.js
> +    && (searchBarApp.search_type !== 'by-company' ||
我想你誤解整個查詢頁面的設計了
我剛把更詳細的內容放到
https://github.com/goodjoblife/WorkTimeSurvey/issues/397

麻煩你去看

從頭到尾沒有 `by-worktime` 這個東西

2017-01-18 13:12 UTC, peteranny commented on src/js/main/show.js
> +    && (searchBarApp.search_type !== 'by-company' ||
我說錯，是by-job-title

2017-01-18 13:54 UTC, closed without merging