預設前 1 % 為隱藏功能
goodjoblife/WorkTimeSurvey pull request #515
Opened 2017-08-27 13:10 UTC by barry800414

2017-08-27 14:01 UTC, mark86092 requested changes

2017-08-27 14:01 UTC, mark86092 commented on src/js/main/show.js
> +        };
L59 ~ L62 是因為什麼？

2017-08-27 14:01 UTC, mark86092 commented on src/js/main/show.js
> +          skip: this.share.view_params.sort_by !== 'created_at',
this.share.view_params.sort_by !== 'created_at' 可能是 true / false，但是 params 是要求 string，這樣可以運作/夠嚴謹嗎？

2017-08-27 14:01 UTC, mark86092 commented on src/views/partials/_show_time_and_salary.pug
> +			button(id="show-extreme" class="extreme-button") {{ show_extreme | extreme_button_text }}
```
button(id="show-extreme" class="extreme-button" v-on:click="xxxxx")
```

xxxxx 可以是 toggle

上面的 jquery 突然插入不知道 side effect 是什麼（會不會重複綁定事件？）

2017-08-27 14:01 UTC, mark86092 commented on src/js/main/show.js
> +});
參見底下的 review，應該用 vue 的方法

2017-08-27 14:01 UTC, mark86092 commented on src/js/main/show.js
> +    toggle_extreme_time_and_salary: function() {
參見底下的 v-on:click，用成 method，這裡的 toggle 我看完的理解應該是 show_extreme 切換

應該沒有到需要從更高層的 app 傳入事件

2017-08-28 01:36 UTC, barry800414 commented
發現排版問題 orz：
![2017-08-28 9 35 07](https://user-images.githubusercontent.com/3805975/29756166-3b1db5bc-8bd4-11e7-93a2-45d088af827a.png)

2017-08-28 02:03 UTC, barry800414 commented
上述的問題都 fix 了，包含排版問題

2017-08-28 17:57 UTC, mark86092 approved these changes

2017-08-28 17:57 UTC, merged